# Generated by Django 2.2.4 on 2019-08-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('PAN_number', models.CharField(max_length=100)),
                ('current_CTC', models.CharField(max_length=100)),
                ('expected_CTC', models.CharField(max_length=100)),
                ('notice_period', models.CharField(max_length=100)),
                ('current_company', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=100)),
                ('preferred_location', models.CharField(max_length=100)),
                ('company_applied', models.CharField(max_length=100)),
                ('position_applied', models.CharField(max_length=100)),
            ],
        ),
    ]
