# Generated by Django 2.2.4 on 2019-08-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0006_auto_20190813_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.CharField(help_text='Add the skill followed by comma', max_length=1000),
        ),
    ]
