# Generated by Django 2.2.4 on 2019-08-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0007_auto_20190817_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='new_experience',
        ),
    ]
