# Generated by Django 2.2.4 on 2019-08-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0008_remove_candidate_new_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='new_experience',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
