# Generated by Django 2.2.4 on 2019-08-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0009_candidate_new_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='new_experience',
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_months',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
