# Generated by Django 2.2.4 on 2019-08-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0013_auto_20190819_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
