# Generated by Django 2.2.4 on 2019-08-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0014_candidate_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='experience',
            new_name='experience_months',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='new_experience',
            new_name='experience_years',
        ),
    ]
