# Generated by Django 2.2.4 on 2019-08-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0015_auto_20190823_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience_months',
            field=models.CharField(help_text='Max. upto 12. If more, consider incrementing years.', max_length=100),
        ),
    ]
