# Generated by Django 2.2.4 on 2019-08-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0016_auto_20190823_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.CharField(help_text='Add the skill followed by comma or space', max_length=1000),
        ),
    ]
