# Generated by Django 2.2.4 on 2019-08-17 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Candidate', '0007_auto_20190817_1547'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0016_company_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_applied', models.CharField(max_length=100)),
                ('current_CTC', models.CharField(max_length=100)),
                ('expected_CTC', models.CharField(max_length=100)),
                ('notice_period', models.CharField(max_length=100)),
                ('candidate_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Shortlisted', 'Interview Scheduled'), ('Interviewed', 'Interviewed'), ('Selected', 'Selected'), ('On-hold', 'On-hold'), ('Rejected', 'Rejected')], default='Submitted', max_length=100)),
                ('relevant_experience', models.CharField(max_length=100)),
                ('total_experience', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Candidate.Candidate')),
                ('company_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tracker',
            },
        ),
    ]
