# Generated by Django 2.2.4 on 2019-08-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20190817_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='user',
        ),
    ]
