# Generated by Django 2.2.4 on 2019-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_remove_tracker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
