# Generated by Django 2.2.4 on 2019-08-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_auto_20190821_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='phone',
        ),
    ]
