# Generated by Django 2.2.4 on 2019-08-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_auto_20190822_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='candidate_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Interview Scheduled', 'Interview Scheduled'), ('Shortlisted', 'Shortlisted'), ('Interviewed', 'Interviewed'), ('Selected', 'Selected'), ('On-hold', 'On-hold'), ('Rejected', 'Rejected')], default='Submitted', max_length=100),
        ),
    ]
