# Generated by Django 2.2.4 on 2019-08-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0011_auto_20190822_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='position_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_openings.Jobb'),
        ),
    ]
