# Generated by Django 2.2.4 on 2019-08-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviews', '0002_interview_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.CharField(max_length=100),
        ),
    ]
