# Generated by Django 2.2.4 on 2019-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviews', '0004_interview_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
