# Generated by Django 2.2.4 on 2019-08-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviews', '0005_interview_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='client',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
