# Generated by Django 2.2.4 on 2019-08-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interviews', '0006_auto_20190822_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='address',
            new_name='interview_address',
        ),
    ]
