# Generated by Django 2.2.4 on 2019-08-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviews', '0009_auto_20190827_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.CharField(help_text='mm/dd/yy format', max_length=10),
        ),
    ]
