# Generated by Django 2.2.4 on 2019-08-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_company_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=10),
        ),
    ]
