# Generated by Django 2.2.4 on 2019-08-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_auto_20190810_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
