# Generated by Django 2.2.4 on 2019-08-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_auto_20190810_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='commercials',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='Audio', max_length=100),
        ),
    ]
