# Generated by Django 2.2.4 on 2019-08-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_company_commercials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='commercials',
        ),
    ]
