# Generated by Django 2.2.4 on 2019-08-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_remove_company_commercials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('choice', models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], default='Fixed', max_length=20)),
                ('tax_choice', models.CharField(choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], default='Inclusive', max_length=20)),
                ('CTC_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Gross', 'Gross')], default='Fixed', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'commercials',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='commercials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Company.Commercials'),
            preserve_default=False,
        ),
    ]
