# Generated by Django 2.2.4 on 2019-08-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_auto_20190817_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='commercials',
        ),
        migrations.AddField(
            model_name='company',
            name='CTC_type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Gross', 'Gross')], default='Fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='choice',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], default='Fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_choice',
            field=models.CharField(choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], default='Inclusive', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='value',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Commercials',
        ),
    ]
