# Generated by Django 2.2.4 on 2019-08-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_auto_20190817_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='choice',
            field=models.CharField(choices=[('Fixed', (('Fixed-Inclusive', 'Fixed-Inclusive'), ('Fixed-Exclusive', 'Fixed-Exclusive'))), ('Percentage', (('Percent-Inclusive', 'Percent-Inclusive'), ('Percent-Exclusive', 'Percent-Exclusive')))], default='Fixed', max_length=20),
        ),
    ]
