# Generated by Django 2.2.4 on 2019-08-17 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_auto_20190817_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
