# Generated by Django 2.2.4 on 2019-08-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0016_company_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='choice',
            new_name='commercials',
        ),
    ]
