# Generated by Django 2.2.4 on 2019-08-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_auto_20190822_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='commercials',
            field=models.CharField(choices=[('Fixed', (('Fixed-Inclusive', 'Fixed-Inclusive'), ('Fixed-Exclusive', 'Fixed-Exclusive'))), ('Percentage', (('Percent-Inclusive of all Taxes', 'Percent-Inclusive of all Taxes'), ('Percent-Exclusive of all Taxes', 'Percent-Exclusive of all Taxes')))], default='Fixed', max_length=20),
        ),
    ]
