# Generated by Django 2.2.4 on 2019-08-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_openings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
