# Generated by Django 2.2.4 on 2019-08-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_openings', '0002_auto_20190814_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('JD_link', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('submission_deadline', models.CharField(max_length=100)),
                ('job_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('On-hold', 'On-hold')], default='Open', max_length=100)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-time', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'jobs',
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
