# Generated by Django 2.2.4 on 2019-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_openings', '0003_auto_20190814_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobb',
            name='submission_deadline',
            field=models.DateField(),
        ),
    ]
