# Generated by Django 2.2.4 on 2019-08-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_openings', '0009_auto_20190816_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobb',
            name='JD_link',
            field=models.URLField(max_length=100),
        ),
    ]
