# Generated by Django 2.2.4 on 2019-08-17 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Job_openings', '0010_auto_20190816_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobb',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
