# Generated by Django 2.2.4 on 2019-08-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_openings', '0011_jobb_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobb',
            name='required_experience',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
