# Generated by Django 2.2.4 on 2019-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.TextField()),
                ('company_name', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('contact_person', models.TextField()),
                ('contact_phone', models.TextField()),
                ('contact_email', models.TextField()),
            ],
        ),
    ]
