# Generated by Django 2.2.4 on 2019-08-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
