# Generated by Django 2.2.4 on 2019-08-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190802_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.TextField()),
                ('experience', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('PAN_number', models.TextField()),
                ('current_CTC', models.TextField()),
                ('expected_CTC', models.TextField()),
                ('notice_period', models.TextField()),
                ('current_company', models.TextField()),
                ('current_location', models.TextField()),
                ('preferred_location', models.TextField()),
                ('company_applied', models.TextField()),
                ('position_applied', models.TextField()),
            ],
        ),
    ]
