# Generated by Django 2.2.4 on 2019-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.TextField()),
                ('position', models.TextField()),
                ('company', models.TextField()),
                ('location', models.TextField()),
                ('JD_link', models.TextField()),
            ],
        ),
    ]
