# Generated by Django 2.2.4 on 2019-08-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190809_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
