# Generated by Django 2.2.4 on 2019-08-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
